CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID SERIAL primary key,
CLIENTE_ID INT,
CHAMADO_ID INT,
VALOR_PAGO DECIMAL(10,2) NOT NULL CHECK (valor_pago > 0),
DATA_PAGAMENTO  DATE NOT NULL,                 
FORMA_PAGAMENTO VARCHAR(50) NOT NULL, 
CONSTRAINT FK_PAGAMENTOS_CLIENTE FOREIGN KEY (PAGAMENTO_ID) REFERENCES PAGAMENTOS(ID) ON DELETE CASCADE,
CONSTRAINT FK_CHAMADO FOREIGN KEY (CHAMADO_ID) REFERENCES CHAMADOS(ID) ON DELETE CASCADE
);(
ID SERIAL primary key,
NOME VARCHAR (100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
TELEFONE VARCHAR(20) UNIQUE NOT NULL,
DATA_CADASTRO  DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS SERVICOS(
ID SERIAL primary key,
NOME VARCHAR(100) NOT NULL,
DESCRICAO TEXT NOT NULL,
PRECO DECIMAL(10, 2) NOT NULL CHECK (preco > 0),
TIPO_SERVICO VARCHAR(50) NOT NULL
CONSTRAINT TIPO_SERVICO CHECK (TIPO_SERVICO IN ('CONSULTORIA', 'SUPORTE', 'MANUTENCAO'))
);


CREATE TABLE IF NOT EXISTS  TECNICOS(
ID SERIAL primary key,
NOME VARCHAR(100) NOT NULL,
ESPECIALIDADES VARCHAR(50) NOT NULL,
DATA_CONTRATACAO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAMADOS(
ID SERIAL primary key,
CLIENTE_ID INT NOT NULL,
SERVICO_ID INT NOT NULL,
TECNICO_ID INT NOT NULL,
DATA_CAHAMADO  DATE NOT NULL,
STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('PENDENTE', 'EM ANDAMENTO', 'FINALIZADO')),
DESCRICAO TEXT NOT NULL,
CONSTRAINT FK_CHAMADO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID) ON DELETE CASCADE,
CONSTRAINT FK_CHAMADO_SERVICO FOREIGN KEY (SERVICO_ID) REFERENCES SERVICOS(ID) ON DELETE CASCADE,
CONSTRAINT FK_CHAMADO_TECNICO FOREIGN KEY (TECNICO_ID) REFERENCES TECNICOS(ID) ON DELETE CASCADE,
CONSTRAINT TIPO_STATUS CHECK (STATUS IN ('PENDENTE', 'EM ANDAMENTO', 'FINALIZADO'))             
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID SERIAL primary key,
CLIENTE_ID INT,
CHAMADO_ID INT,
VALOR_PAGO DECIMAL(10,2) NOT NULL CHECK (valor_pago > 0),
DATA_PAGAMENTO DATE NOT NULL,                 
FORMA_PAGAMENTO VARCHAR(50) NOT NULL, 
CONSTRAINT FK_PAGAMENTOS_CLIENTE FOREIGN KEY (PAGAMENTO_ID) REFERENCES PAGAMENTOS(ID) ON DELETE CASCADE,
CONSTRAINT FK_CHAMADO FOREIGN KEY (CHAMADO_ID) REFERENCES CHAMADOS(ID) ON DELETE CASCADE
);


INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, DATA_CADSTRADA)
VALUES ('JOÃO SILVA', 'joao@email.com', '(11)98765-4321', '2023-01-15'),
        ('MARIA OLIVEIRA', 'maria@email.com', '(21)99654-3210', '2023-02-20'),
		('PEDRO SOUZA', 'pedro@email.com', '(31)99765-1234', '2023-03-10'),
		('ANA COSTA', 'ana@email.com', '(41)98888-9999', '2023-04-25'),
		('LUCAS ALMEIDA', 'lucas@email.com', '(61)99123-4567', '2023-05-30');
		
		SELECT * FROM CLIENTES; 

INSERT INTO SERVICOS (NOME, DESCRICAO, PRECO, TIPO_SERVICO)
VALUES ('CONSULTORIA EM TI', 'CONSULTORIA ESPECIALIZADA EM INFRAESTRUTURA DE TI' '500.00', 'CONSULTORIA'),
       ('MANUTENÇÃO DE EQUIPAMENTOS', 'EQUIPAMENTOS MANUTENÇÃO PREVENTIVA E CORRERTIVA DE EQUIPAMENTOS', '300,00', 'MANUTENÇÃO')
        ('SUPORTE TÉCNICO', 'SUPORTE REMOTO E PRESENCIAL PARA EMPRESAS', '200.00'. 'Suporte')
		
		SELECT * FROM SERVICOS;

INSERT INTO TECNICOS (NOME, ESPECIALIDADE, DATA_CONTRATACAO)
VALUES ('CARLOS OLIVEIRA', 'CONSULTORIA TI', '2022-10-10'),
       ('FERNANDA SOUZA', 'MANUTENÇÃO', '2021-06-15'),
	   ('ROBERTO COSTA', 'SUPORTE TÉCNICO', '2020-08-20');

	   SELECT * FROM TECNICOS;

INSERT INTO CHAMADOS_ID (CLIENTE_ID, TECNICO_ID, SERVICO_ID, DATA_CHAMADO, STATUS, DESCRICAO)
VALUES (1, 1, 1, '2023-06-01', 'PENDENTE REPARO NO CABEAMENTO DE REDE'),
        (2, 2, 2, '2023-07-10' 'EM ANDAMENTO MANUTENCAO NO SERVIDOR'),
		(3, 3, 3, '2023-08-05', 'FINALIZADO CONFIGURACAO DE SOFTWARE EMPRESARIAL'),
		(4, 1, 2, '2023-09-20', 'PENDENTE', 'MANUTENCAO DE COMPUTADOR'),
		(5, 2, 1, '2023-10-15', 'FINALIZADO SUPORTE PARA SOFTWARE');

		SELECT * FROM CHAMADOS;

ALTER TABLE PAGAMENTOS ADD COLUMN DATA_PAGAMENTO DATE NOT NULL;

ALTER TABLE PAGAMENTOS ADD COLUMN FORMA_PAGEMNTO VARCHAR(50) NOT NULL;



INSERT INTO PAGAMENTOS (CLIENTE_ID, CHAMADO_ID, VALOR_PAGO, DATA_PAGAEMNTO, FORMA_PAGAEMNTO)
VALUES ('1', '1', '350.00', '2023-06-15', 'CARTAO DE CREDITO'),
        ('2', '2', '450.00', '2023-07-15', 'CARTAO OU PIX'),
		('3', '3', '600.00', '2023-08-10', 'PIX'),
		('4', '4', '300.00', '2023-09-25', 'PIX')

		SELECT * FROM PAGAMENTOS
		
