--CRIANDO UM BANCO DE DADOS (DATABASE)
--CREATE DATABASE aula0312

-- Criando um tabela
--CREATE TABLE IF NOT EXISTS PRODUTO(
--ID INT PRIMARY KEY, 
--COD VARCHAR(4) NOT NULL UNIQUE,
--NOME VARCHAR(100) NOT NULL,
--PRECO REAL CHECK(PRECO>0)
--);
--CREATE TABLE IF NOT EXISTS PRODUTO01(
--ID INT PRIMARY KEY, 
--COD VARCHAR(4) NOT NULL UNIQUE,
--NOME VARCHAR(100) NOT NULL,
--PRECO REAL CHECK(PRECO>0)
--);
--\dt; (descrição das estruturas do banco);
--\d PRODUTO;
--Deletando uma base de dados
--DROP DATABASE aula0312;
--Deletando um atabela
--DROP TABLE PRODUTO;
--\dt;





--\dt;
--CREATE TABLE IF NOT EXISTS PROFESSOR(
--ID INT PRIMARY KEY,
--NOME VARCHAR(100) NOT NULL,
--CPF CHAR (11) UNIQUE NOT NULL
--);

--CREATE TABLE IF NOT EXISTS TURMA(
--ID INT,
--NUMERO INT,
--DURACAO_DIAS INT,
--ID_PROFESSOR INT,
--PRIMARY KEY(ID, NUMERO),
--CONSTRAINT fk_prof FOREIGN KEY(ID_PROFESSOR) REFERENCES PROFESSOR(ID)
--);

--\dt
--\d turma
--\d professor


CREATE TABLE IF NOT EXISTS FORNECEDOR(
ID INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CIDADE VARCHAR(30)  NOT NULL
);

CREATE TABLE IF NOT EXISTS PECA(
ID INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DESCRICAO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDA(
ID_FORNECEDOR  INT,
ID_PECA INT,
DATA DATE NOT NULL,
QUANTIDADE INT NOT NULL,
CONSTRAINT fk_fornecedor FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID),
CONSTRAINT fk_peca FOREIGN KEY(ID_PECA) REFERENCES PECA(ID)
);


ALTER TABLE fornecedor
ADD COLUMN telefone CHAR(11);

ALTER TABLE PECA
ADD COLUMN PRECO INT;

ALTER TABLE fornecedor
DROP COLUMN CIDADE;


\dt;
\d fornecedor;
\d PECA;
\d venda;


